[package]
name = "gossamer"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.2"
actix-web = "4.1.0"
askama = "0.11.1"
dotenv = "0.15.0"
harsh = "0.2.2"
rocksdb = { version = "0.19.0", features = ["multi-threaded-cf"] }
serde = { version = "1.0.144", features = ["derive"] }
thiserror = "1.0.32"
url = "2.2.2"

[lib]
name = "gossamer"
path = "src/lib.rs"

[[bin]]
name = "gossamer"
path = "src/bin/main.rs"

[profile.release]
lto = "thin"
