[package]
name = "gossamer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.0"
actix-web = "4.0.1"
askama = "0.11.1"
dotenv = "0.15.0"
harsh = "0.2.2"
rocksdb = { git = "https://github.com/rust-rocksdb/rust-rocksdb.git", rev = "ef8724679857139ede30672a8c478b6ade5ef0a4", features = [
  "multi-threaded-cf",
] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
url = "2.2.2"

[lib]
name = "gossamer"
path = "src/lib.rs"

[[bin]]
name = "gossamer"
path = "src/bin/main.rs"

[profile.release]
codegen-units = 1
opt-level = 3
lto = true