[package]
name = "gossamer"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.0"
askama = "0.11.1"
dotenv = "0.15.0"
harsh = "0.2.2"
once_cell = "1.17.0"
rocksdb = { version = "0.19.0", features = ["multi-threaded-cf"] }
serde = { version = "1.0.152", features = ["derive"] }
thiserror = "1.0.38"
url = "2.3.1"

[lib]
name = "gossamer"
path = "src/lib.rs"

[[bin]]
name = "gossamer"
path = "src/main.rs"

[profile.release]
lto = "thin"
